# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5b224eb72c14acd80e851123ccdd8b1c837663beb935726dcb234036562ffef9ed64eb967b38c02e6622a804920f2864fed61b31ac8ad9fb76b231b34f916c66

test:
  secret_key_base: b83d89784445c917539c3fa511ff31d581ab930103d36f364bd5d4e08ac8bbe85028b08605fd8906c9b7ea6aead1db1b9fad843aee27f81e406df26a30b7ea2a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
